### PR TITLE
Create Appetizer menu and add one beverage

### PR DESCRIPTION
**Pull request by Jangsoodlor**

### CODE REVIEW

**Comment by knilios** [comment]
image
No need to write your name here, I think. Other than that, Everything looks fine.

**Comment by Pawat-Sarnchawanakit** [comment]
Appetizer link broken, clicking it doesn't bring it to the correct section, try making the thing after '#' lowercase.
image

**Comment by Jangsoodlor** [comment]
both issues has been fixed

**Comment by Pawat-Sarnchawanakit** [comment]
Inconsistent italics: Beverages names aren't italics like the appetizer name.
Name or food name?
It has been decided in Discord that the first column of the menu shall be Food Name

**Comment by Jangsoodlor** [comment]
fixed

**Comment by knilios** [comment]
Everything seems fine.

**Pull request merged**
