### PR TITLE
Created desserts menu and added one beverage.

### PR DESCRIPTION
**Pull request by BioB3**

### CODE REVIEW

**Comment by Jangsoodlor** [comment]
You seem to forgot to add your section to the `README.md` file

**Comment by knilios** [comment]
image
Please remove this

**Comment by knilios** [comment]
You have to add yourself into the contributors list and remove Bill Gates from there

**Comment by BioB3** [comment]
The issue has been fixed.

**Comment by jbrucker** [comment]
Good.  This shows you are doing a serious review of work.

**Pull request merged**
