### PR TITLE
Created a soup menu and added one beverage.

### PR DESCRIPTION
**Pull request by knilios**

### CODE REVIEW

**Comment by Jangsoodlor** [comment]
image
There's a "!" sign before your beverage pic. And I don't know wheter the "Section" after "Soup Menu" is neccessary. Otherwise it's ok!

**Comment by knilios** [comment]
I have resolved the "!" sign issue.

**Comment by Pawat-Sarnchawanakit** [comment]
Remove unneccessary `the` `... boiled the salmon ...`
```
A simple but delicious soup will make you happy. We boiled the salmon sushi to perfection, so it is tender and chewy
```
Remove unnecessary `it` `... eat it at ...`
```
A luxurious soup Thai people often eat it at the end of the month. The fish bone is soft and delicious!
```

**Comment by Pawat-Sarnchawanakit** [comment]
image

**Comment by knilios** [comment]
fixed the issue

**Pull request merged**
